// apps/angular-demo/src/app/cart/cart.page.ts
import { Component, inject } from '@angular/core';
import { toSignal } from '@state-adapt/angular';

import { formatPrice, products } from './cart.adapter';
import { CartStores } from './cart.store';

@Component({
  standalone: true,
  selector: 'sa-cart-page',
  preserveWhitespaces: false,
  template: `
    <section class="panel">
      <h1>Cart</h1>
      <p class="muted">
        The cart and the coupon are two separate stores. <code>joinStores</code>
        derives the discount and total across both — neither store imports the other.
      </p>
    </section>

    <section class="card-grid products">
      @for (product of products; track product.id) {
        <article class="card static product">
          <span class="emoji" aria-hidden="true">{{ product.emoji }}</span>
          <h2>{{ product.name }}</h2>
          <p class="muted">{{ formatPrice(product.price) }}</p>
          <button
            class="button primary"
            [attr.data-testid]="'add-' + product.id"
            (click)="cart.add(product.id)"
          >
            Add to cart
          </button>
        </article>
      }
    </section>

    <section class="panel">
      <h2>Your cart</h2>

      @if (cart.isEmpty()) {
        <p class="muted empty" data-testid="cart-empty">Your cart is empty.</p>
      } @else {
        <ul class="cart-list" data-testid="cart-list">
          @for (line of cart.lines(); track line.product.id) {
            <li [attr.data-testid]="'cart-line-' + line.product.id">
              <span class="emoji" aria-hidden="true">{{ line.product.emoji }}</span>
              <span class="cart-name">{{ line.product.name }}</span>
              <div class="qty">
                <button
                  [attr.aria-label]="'Remove one ' + line.product.name"
                  [attr.data-testid]="'decrease-' + line.product.id"
                  (click)="cart.removeOne(line.product.id)"
                >
                  −
                </button>
                <span [attr.data-testid]="'qty-' + line.product.id">{{ line.quantity }}</span>
                <button
                  [attr.aria-label]="'Add one ' + line.product.name"
                  [attr.data-testid]="'increase-' + line.product.id"
                  (click)="cart.add(line.product.id)"
                >
                  +
                </button>
              </div>
              <span
                class="line-total"
                [attr.data-testid]="'line-total-' + line.product.id"
                >{{ formatPrice(line.product.price * line.quantity) }}</span
              >
              <button
                class="icon danger"
                [attr.aria-label]="'Remove all ' + line.product.name"
                [attr.data-testid]="'remove-' + line.product.id"
                (click)="cart.removeAll(line.product.id)"
              >
                ✕
              </button>
            </li>
          }
        </ul>
      }

      <label class="field">
        <span>
          Coupon code <span class="muted small">(try ADAPT10 or STATE25)</span>
        </span>
        <input
          type="text"
          placeholder="Coupon code"
          data-testid="coupon-input"
          [value]="coupon()"
          (input)="coupon.set($any($event.target).value)"
        />
      </label>

      @if (coupon.isValid()) {
        <p class="note ok" data-testid="coupon-valid">
          {{ coupon.code() }} applied — {{ round(coupon.discountRate() * 100) }}% off
        </p>
      }
      @if (coupon.isRejected()) {
        <p class="note bad" data-testid="coupon-invalid">
          {{ coupon.code() }} isn't a valid code
        </p>
      }

      <dl class="totals">
        <div>
          <dt>Items</dt>
          <dd data-testid="cart-count">{{ cart.itemCount() }}</dd>
        </div>
        <div>
          <dt>Subtotal</dt>
          <dd data-testid="cart-subtotal">{{ formatPrice(cart.subtotal()) }}</dd>
        </div>
        <div>
          <dt>Discount</dt>
          <dd data-testid="cart-discount">−{{ formatPrice(discount()) }}</dd>
        </div>
        <div class="grand">
          <dt>Total</dt>
          <dd data-testid="cart-total">{{ formatPrice(total()) }}</dd>
        </div>
      </dl>
    </section>
  `,
})
export class CartPageComponent {
  products = products;
  formatPrice = formatPrice;
  round = Math.round;

  private stores = inject(CartStores);
  cart = this.stores.cart;
  coupon = this.stores.coupon;
  discount = toSignal(this.stores.checkout.discount$, { initialValue: 0 });
  total = toSignal(this.stores.checkout.total$, { initialValue: 0 });
}

// apps/react-demo/src/app/cart/cart.page.tsx
import React from 'react';
import { useStore } from '@state-adapt/react';

import { formatPrice, products } from './cart.adapter';
import { cartStore, checkoutStore, couponStore } from './cart.store';

export function CartPage() {
  const [cart, cartActions] = useStore(cartStore);
  const [coupon, couponActions] = useStore(couponStore);
  const [checkout] = useStore(checkoutStore);

  return (
    <>
      <section className="panel">
        <h1>Cart</h1>
        <p className="muted">
          The cart and the coupon are two separate stores. <code>joinStores</code>{' '}
          derives the discount and total across both — neither store imports the other.
        </p>
      </section>

      <section className="card-grid products">
        {products.map(product => (
          <article className="card static product" key={product.id}>
            <span className="emoji" aria-hidden="true">
              {product.emoji}
            </span>
            <h2>{product.name}</h2>
            <p className="muted">{formatPrice(product.price)}</p>
            <button
              className="button primary"
              data-testid={`add-${product.id}`}
              onClick={() => cartActions.add(product.id)}
            >
              Add to cart
            </button>
          </article>
        ))}
      </section>

      <section className="panel">
        <h2>Your cart</h2>

        {cart.isEmpty ? (
          <p className="muted empty" data-testid="cart-empty">
            Your cart is empty.
          </p>
        ) : (
          <ul className="cart-list" data-testid="cart-list">
            {cart.lines.map(({ product, quantity }) => (
              <li key={product.id} data-testid={`cart-line-${product.id}`}>
                <span className="emoji" aria-hidden="true">
                  {product.emoji}
                </span>
                <span className="cart-name">{product.name}</span>
                <div className="qty">
                  <button
                    aria-label={`Remove one ${product.name}`}
                    data-testid={`decrease-${product.id}`}
                    onClick={() => cartActions.removeOne(product.id)}
                  >
                    −
                  </button>
                  <span data-testid={`qty-${product.id}`}>{quantity}</span>
                  <button
                    aria-label={`Add one ${product.name}`}
                    data-testid={`increase-${product.id}`}
                    onClick={() => cartActions.add(product.id)}
                  >
                    +
                  </button>
                </div>
                <span className="line-total" data-testid={`line-total-${product.id}`}>
                  {formatPrice(product.price * quantity)}
                </span>
                <button
                  className="icon danger"
                  aria-label={`Remove all ${product.name}`}
                  data-testid={`remove-${product.id}`}
                  onClick={() => cartActions.removeAll(product.id)}
                >
                  ✕
                </button>
              </li>
            ))}
          </ul>
        )}

        <label className="field">
          <span>
            Coupon code <span className="muted small">(try ADAPT10 or STATE25)</span>
          </span>
          <input
            type="text"
            placeholder="Coupon code"
            data-testid="coupon-input"
            value={coupon.state}
            onChange={event => couponActions.set(event.target.value)}
          />
        </label>

        {coupon.isValid && (
          <p className="note ok" data-testid="coupon-valid">
            {coupon.code} applied — {Math.round(coupon.discountRate * 100)}% off
          </p>
        )}
        {coupon.isRejected && (
          <p className="note bad" data-testid="coupon-invalid">
            {coupon.code} isn&apos;t a valid code
          </p>
        )}

        <dl className="totals">
          <div>
            <dt>Items</dt>
            <dd data-testid="cart-count">{cart.itemCount}</dd>
          </div>
          <div>
            <dt>Subtotal</dt>
            <dd data-testid="cart-subtotal">{formatPrice(cart.subtotal)}</dd>
          </div>
          <div>
            <dt>Discount</dt>
            <dd data-testid="cart-discount">−{formatPrice(checkout.discount)}</dd>
          </div>
          <div className="grand">
            <dt>Total</dt>
            <dd data-testid="cart-total">{formatPrice(checkout.total)}</dd>
          </div>
        </dl>
      </section>
    </>
  );
}
