// apps/react-demo/src/app/live/live-ticker.tsx
import React from 'react';
import { useStore } from '@state-adapt/react';

import { lifecycleStore, tickerStore } from './live.store';

/**
 * Subscribing to `tickerStore` is what activates it. Rendering this on more than
 * one route is what makes the store "shared".
 */
export function LiveTicker({ label }: { label?: string }) {
  const [ticker] = useStore(tickerStore);

  return (
    <div className="ticker" data-testid="ticker">
      <span className="ticker-dot" aria-hidden="true" />
      <span>
        {label ?? 'Shared ticker'}: <strong data-testid="ticker-count">{ticker.state}</strong>{' '}
        <span className="muted small">({ticker.label})</span>
      </span>
    </div>
  );
}

/**
 * A subscriber with no UI of its own. Mounted from the shell, it holds the
 * ticker store active across every route.
 */
export function TickerKeepAlive() {
  useStore(tickerStore);
  return null;
}

/** Always-visible readout of the ticker store's subscription lifecycle. */
export function TickerLifecycle() {
  const [lifecycle] = useStore(lifecycleStore);

  return (
    <span className="lifecycle">
      ticker store:{' '}
      <strong
        className={lifecycle.isSubscribed ? 'ok' : 'off'}
        data-testid="ticker-status"
      >
        {lifecycle.state.status}
      </strong>{' '}
      <span className="muted small">
        (<span data-testid="ticker-activations">{lifecycle.state.activations}</span>{' '}
        activations, <span data-testid="ticker-teardowns">{lifecycle.state.teardowns}</span>{' '}
        teardowns)
      </span>
    </span>
  );
}

// apps/angular-demo/src/app/live/live-ticker.ts
import { Component, Input, inject } from '@angular/core';

import { LiveStores } from './live.store';

/**
 * Reading `ticker` in the template is what activates it. Rendering this on more
 * than one route is what makes the store "shared".
 */
@Component({
  standalone: true,
  selector: 'sa-live-ticker',
  preserveWhitespaces: false,
  template: `
    <div class="ticker" data-testid="ticker">
      <span class="ticker-dot" aria-hidden="true"></span>
      <span>
        {{ label }}: <strong data-testid="ticker-count">{{ ticker() }}</strong>
        <span class="muted small">({{ ticker.label() }})</span>
      </span>
    </div>
  `,
})
export class LiveTickerComponent {
  @Input() label = 'Shared ticker';
  ticker = inject(LiveStores).ticker;
}

/**
 * A subscriber with no UI of its own. Mounted from the shell, it holds the
 * ticker store active across every route.
 */
@Component({
  standalone: true,
  selector: 'sa-ticker-keep-alive',
  host: { style: 'display: none' },
  template: '{{ ticker() }}',
})
export class TickerKeepAliveComponent {
  ticker = inject(LiveStores).ticker;
}

/** Always-visible readout of the ticker store's subscription lifecycle. */
@Component({
  standalone: true,
  selector: 'sa-ticker-lifecycle',
  preserveWhitespaces: false,
  template: `
    <span class="lifecycle">
      ticker store:
      <strong
        [class.ok]="lifecycle.isSubscribed()"
        [class.off]="!lifecycle.isSubscribed()"
        data-testid="ticker-status"
        >{{ lifecycle().status }}</strong
      >
      <span class="muted small">
        (<span data-testid="ticker-activations">{{ lifecycle().activations }}</span>
        activations,
        <span data-testid="ticker-teardowns">{{ lifecycle().teardowns }}</span>
        teardowns)
      </span>
    </span>
  `,
})
export class TickerLifecycleComponent {
  lifecycle = inject(LiveStores).lifecycle;
}
