// apps/angular-demo/src/app/crew/components/crew-hero.ts
import { Component, inject } from '@angular/core';

import { CrewStores } from '../crew.store';
import { CrewStatComponent } from './crew-stat';

@Component({
  selector: 'sa-crew-hero',
  imports: [CrewStatComponent],
  template: `
    <section class="panel crew-hero">
      <div>
        <p class="eyebrow">Entity adapter showcase</p>
        <h1>Flight Operations</h1>
        <p class="muted">
          One normalized roster powers this dashboard, its filtered views, bulk commands,
          and every detail page.
        </p>
      </div>
      <div class="crew-stats" aria-label="Roster statistics">
        <sa-crew-stat label="Roster" [value]="crew.count()" testId="crew-count" />
        <sa-crew-stat
          label="Active"
          [value]="crew.activeCount()"
          testId="crew-active-count"
        />
        <sa-crew-stat
          label="Flight ready"
          [value]="crew.availableCount()"
          testId="crew-available-count"
        />
        <sa-crew-stat
          label="Selected"
          [value]="crew.selectedCount()"
          testId="crew-selected-count"
        />
      </div>
    </section>
  `,
})
export class CrewHeroComponent {
  crew = inject(CrewStores).crew;
}

// apps/react-demo/src/app/crew/components/crew-hero.tsx
import React from 'react';
import { useStore } from '@state-adapt/react';

import { crewStore } from '../crew.store';
import { CrewStat } from './crew-stat';

export function CrewHero() {
  const [crew] = useStore(crewStore);

  return (
    <section className="panel crew-hero">
      <div>
        <p className="eyebrow">Entity adapter showcase</p>
        <h1>Flight Operations</h1>
        <p className="muted">
          One normalized roster powers this dashboard, its filtered views, bulk commands,
          and every detail page.
        </p>
      </div>
      <div className="crew-stats" aria-label="Roster statistics">
        <CrewStat label="Roster" value={crew.count} testId="crew-count" />
        <CrewStat label="Active" value={crew.activeCount} testId="crew-active-count" />
        <CrewStat
          label="Flight ready"
          value={crew.availableCount}
          testId="crew-available-count"
        />
        <CrewStat
          label="Selected"
          value={crew.selectedCount}
          testId="crew-selected-count"
        />
      </div>
    </section>
  );
}
