// apps/angular-demo/src/app/crew/components/crew-list.ts
import { Component, input } from '@angular/core';

import { CrewMember } from '../crew.adapter';
import { CrewFilter } from '../crew.types';
import { CrewCardComponent } from './crew-card';

@Component({
  selector: 'sa-crew-list',
  imports: [CrewCardComponent],
  template: `
    <section class="crew-list" data-testid="crew-list">
      @for (member of visible(); track member.callSign) {
        <sa-crew-card [member]="member" />
      }
      @if (!visible().length) {
        <p class="panel muted empty" data-testid="crew-empty">
          No crew match the <strong>{{ filter() }}</strong> view.
        </p>
      }
    </section>
  `,
})
export class CrewListComponent {
  visible = input.required<CrewMember[]>();
  filter = input.required<CrewFilter>();
}

// apps/react-demo/src/app/crew/components/crew-list.tsx
import React from 'react';

import { CrewMember } from '../crew.adapter';
import { CrewFilter } from '../crew.types';
import { CrewCard } from './crew-card';

export function CrewList({
  visible,
  filter,
}: {
  visible: CrewMember[];
  filter: CrewFilter;
}) {
  return (
    <section className="crew-list" data-testid="crew-list">
      {visible.map(member => (
        <CrewCard member={member} key={member.callSign} />
      ))}
      {!visible.length && (
        <p className="panel muted empty" data-testid="crew-empty">
          No crew match the <strong>{filter}</strong> view.
        </p>
      )}
    </section>
  );
}
